<a href="https://colab.research.google.com/github/Adyypower/Deep-learning-Models-or-topics/blob/main/2_tokenizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
from transformers import BertModel , AutoTokenizer
import pandas as pd
from scipy.spatial.distance import cosine

In [3]:
model_name = 'bert-base-cased'
model = BertModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [4]:
sentence = "When life gives you lemons, don`t make lemonad"
tokens = tokenizer.tokenize(sentence)
print(tokens)

['When', 'life', 'gives', 'you', 'lemon', '##s', ',', 'don', '`', 't', 'make', 'lemon', '##ad']

In [5]:
vocab = tokenizer.vocab
vocab

{'##ッ': 28843,
 '##§': 28161,
 'Tex': 18033,
 'sliding': 7989,
 'AB': 16151,
 'Dex': 23058,
 'Georgie': 22186,
 'Ellie': 10622,
 '##ding': 3408,
 'Singers': 24047,
 'postal': 14889,
 'Bell': 4720,
 '》': 888,
 '##rds': 15093,
 '##„': 28693,
 'Due': 4187,
 'six': 1565,
 'sandstone': 13145,
 'arena': 8176,
 'Ah': 7066,
 '1796': 14342,
 '##К': 28375,
 'Index': 10146,
 '##bra': 6766,
 'Prague': 8254,
 'ease': 7166,
 'リ': 969,
 '##kata': 24011,
 'France': 1699,
 'ּ': 534,
 '##ingly': 15809,
 'oblique': 23455,
 'ュ': 967,
 '##NP': 14576,
 'Smile': 21278,
 'Colours': 23189,
 'Т': 465,
 'distinct': 4966,
 'withdrawal': 10602,
 'left': 1286,
 '`': 169,
 'Bernhard': 23627,
 'flow': 4235,
 'Württemberg': 17565,
 'shocking': 19196,
 'Wisconsin': 4486,
 'scrub': 20712,
 'butcher': 26087,
 'nursery': 17840,
 '##nco': 23573,
 'Hagen': 27080,
 'ﬂ': 1095,
 'Certificate': 14972,
 'epithet': 21397,
 'policing': 27841,
 'Kane': 8119,
 '##ël': 17259,
 'predictions': 23770,
 'Alongside': 26589,
 '1907': 4796,
 'locked': 4594,
 'bright': 3999,
 'prediction': 20770,
 'visitors': 5496,
 'ft': 2167,
 'Train': 9791,
 '##ely': 17328,
 'Skin': 20616,
 'fed': 7672,
 'simplest': 23565,
 'refusal': 14686,
 'AM': 6586,
 'Bridget': 20907,
 'assembly': 5839,
 '##Í': 28188,
 'oven': 19645,
 '##nja': 19926,
 'recruits': 16231,
 'Reno': 19139,
 '##apa': 26519,
 '##rit': 7729,
 '##lesh': 27548,
 '##imus': 26552,
 'preacher': 18154,
 'serve': 2867,
 'expansion': 4298,
 'insist': 19831,
 'collapsing': 26092,
 'random': 7091,
 'appoint': 18016,
 'lipstick': 28005,
 'needy': 27819,
 'Argentine': 8106,
 'Hardy': 10092,
 'Treatment': 19165,
 'pole': 7712,
 'yo': 26063,
 'liked': 3851,
 'pupils': 7035,
 '##osis': 11776,
 'organisms': 12023,
 'Institutes': 24496,
 'tongue': 3661,
 'Compared': 22439,
 '##ւ': 28436,
 'heel': 12781,
 'Turkey': 4439,
 '##え': 28789,
 '##arte': 26579,
 '##ح': 28480,
 'vector': 9479,
 'constituted': 12810,
 'chancel': 17954,
 'ם': 547,
 '159': 20485,
 'Minority': 26495,
 'sunk': 10406,
 '##道': 28967,
 'Blaze': 27740,
 'strange': 4020,
 'Water': 4434,
 'sweep': 12245,
 'dating': 4676,
 'parameter': 17816,
 'notorious': 14140,
 'Ulrich': 21351,
 '196': 21846,
 '##list': 7276,
 'liability': 15509,
 '##pher': 15940,
 'Calendar': 26208,
 'Thorpe': 22237,
 'dresses': 15402,
 'Swami': 22762,
 '##ched': 6428,
 'Š': 322,
 'completely': 2423,
 'valley': 4524,
 'slight': 6812,
 'Giving': 22700,
 'Wilson': 3425,
 'Garcia': 10233,
 'Brooke': 11559,
 'Ginger': 20326,
 'failure': 4290,
 '##rants': 18937,
 'cereal': 24759,
 'prefix': 19586,
 'Lille': 25411,
 'certainty': 17140,
 'transit': 9575,
 'Hugo': 9110,
 'suspicious': 10108,
 'lever': 20097,
 '96': 5306,
 '##ood': 13465,
 '##lium': 14635,
 'Ham': 13030,
 'Tracy': 10435,
 'biting': 13602,
 'imposed': 9520,
 'Darwin': 11555,
 '##hawk': 19952,
 'dean': 14445,
 '##udo': 18109,
 'Theme': 14999,
 '130': 7029,
 'motivation': 15710,
 'prophecy': 19214,
 'solvent': 27624,
 'worthless': 26121,
 'family': 1266,
 'aspect': 7631,
 'chicken': 9323,
 'inspire': 21792,
 'terminal': 6020,
 'snatched': 14779,
 'syndrome': 9318,
 'theme': 3815,
 '##る': 28821,
 'petitioned': 25042,
 '241': 24776,
 'feathers': 13311,
 'Progressive': 10709,
 'ensure': 4989,
 'Indo': 11501,
 'lashes': 17366,
 'Country': 3898,
 'adequate': 12373,
 '##rter': 27618,
 'Emilia': 22836,
 'Territories': 18057,
 '##田': 28950,
 'resting': 8137,
 'capitals': 24199,
 'sexual': 3785,
 'Turner': 6217,
 '##cid': 16388,
 'Chang': 11497,
 'Sheikh': 13609,
 'complicated': 8277,
 'minded': 13767,
 'kissing': 7567,
 'Anyone': 15859,
 'landings': 18482,
 'vowel': 13283,
 'popped': 10447,
 'tightened': 7974,
 'prosecutor': 16810,
 'homosexuality': 18160,
 'flags': 14870,
 '##ṇ': 28636,
 'Nurse': 17418,
 'compensate': 20766,
 'blast': 9232,
 'Se': 22087,
 '126': 14491,
 '##ddling': 16166,
 'recorded': 1802,
 'Sakura': 26364,
 'Examples': 10839,
 '##oe': 7745,
 'marsh': 22295,
 '##gene': 27054,
 'frightening': 18523,
 'Purple': 13773,
 'Mason': 6287,
 'é': 255,
 'memorial': 6768,
 'Flames': 19002,
 '##mu': 13601,
 'beverage': 24802,
 '##dust': 27650,
 'location': 2450,
 'Listed': 22109,
 'orders': 3791,
 'proposed': 3000,
 'lucrative': 23284,
 'Morrow': 23611,
 'dash': 16605,
 'lengths': 10707,
 'drum': 7505,
 'beacon': 25973,
 'Ç': 232,
 'Eric': 3601,
 'wonders': 21346,
 'SAT': 26203,
 'painters': 15233,
 'junction': 6698,
 'Ivory': 17507,
 'Lyon': 10067,
 'segregation': 21079,
 '##Я': 28392,
 'implies': 12942,
 'filters': 19690,
 '##rov': 12316,
 '##ジ': 28838,
 'yard': 3723,
 'League': 1453,
 '##力': 28885,
 '##hal': 7654,
 '18th': 4186,
 'Jaguar': 21694,
 '##Ш': 28389,
 'absent': 10040,
 'meta': 27154,
 '##plied': 18148,
 'monitored': 19232,
 '##ane': 6354,
 'gives': 3114,
 'XV': 16925,
 '1909': 4818,
 'libraries': 9818,
 'Trinity': 6626,
 'Tennis': 9968,
 'Southeast': 8348,
 'transferring': 15273,
 '##puted': 18505,
 'ེ': 696,
 'Nik': 27051,
 'investment': 5151,
 'simply': 2566,
 'drilled': 27504,
 'leaves': 2972,
 'playground': 18514,
 'week': 1989,
 'Schumacher': 24656,
 'Roberto': 10599,
 'rivals': 9521,
 'announce': 15810,
 'Standing': 9996,
 'Fest': 22305,
 'tailored': 24423,
 '##گ': 28504,
 'Infantry': 4155,
 'estimate': 10301,
 '##rrows': 24847,
 'Writer': 12515,
 'dividing': 18699,
 'her': 1123,
 'Sunderland': 16362,
 '##ynasties': 25643,
 'ط': 581,
 '##yres': 19168,
 '##gnolia': 27795,
 'backgrounds': 16497,
 '##té': 14608,
 '##let': 5765,
 'ù': 271,
 'booklet': 21757,
 'Season': 5623,
 'Tristan': 9665,
 'Nr': 26378,
 'vocational': 18341,
 'Raven': 11520,
 'Grimm': 27354,
 '##kara': 14567,
 'Basic': 11568,
 'choices': 9940,
 '₂': 813,
 '##itation': 12633,
 'Lines': 12058,
 'Learning': 9681,
 'Christianity': 7522,
 'youthful': 25708,
 'skating': 12718,
 'reluctance': 24072,
 'Brandt': 21140,
 'Wyoming': 10513,
 'expertise': 11717,
 '車': 1072,
 '##29': 26752,
 'encourages': 17233,
 'ե': 516,
 'Playing': 15628,
 'Volleyball': 13741,
 'commissioner': 12425,
 '##log': 13791,
 '##̍': 28312,
 'Ñ': 237,
 'stalked': 16895,
 '##pore': 21370,
 'Л': 458,
 'edition': 2596,
 'Happiness': 25410,
 'diamond': 9883,
 'chaired': 12624,
 '##∧': 28750,
 'commercially': 11514,
 '##imate': 15774,
 '208': 19980,
 '1A': 26637,
 'Strategy': 18050,
 '##ye': 4980,
 'plots': 15836,
 'supplied': 7694,
 'Nigerian': 11960,
 'land': 1657,
 'commanders': 12392,
 '##₈': 28715,
 'horrible': 9210,
 'wore': 4307,
 '##ceive': 23566,
 'Inspired': 23865,
 'Swimming': 14899,
 'co': 1884,
 'air': 1586,
 'Suburban': 24909,
 'Parts': 16633,
 'ore': 12327,
 'shone': 15515,
 'ƒ': 341,
 'bundled': 28003,
 'Sites': 27010,
 '##ester': 12831,
 'Siberian': 24196,
 'advertisements': 15448,
 'small': 1353,
 'Gaga': 26936,
 'assumed': 4260,
 'woods': 6269,
 'berth': 18690,
 'bitten': 21381,
 'superior': 7298,
 'Tribal': 24252,
 '##wheel': 26587,
 '##dom': 9277,
 'wars': 8755,
 'With': 1556,
 '##gnetic': 19975,
 'division': 2417,
 'Violence': 19834,
 'variety': 2783,
 '##BE': 27211,
 'WR': 26476,
 '##ends': 22367,
 'Orlando': 9906,
 'Landmark': 18405,
 'ὁ': 770,
 '##Á': 28180,
 'beasts': 18914,
 'induction': 18293,
 'Tito': 22754,
 '##ivated': 17894,
 'challenging': 10467,
 '##GP': 17095,
 '##ntino': 18618,
 'dominance': 14678,
 '##ardt': 25018,
 'Bombay': 11888,
 'satellite': 5989,
 'touches': 13193,
 'liberal': 7691,
 'occurred': 3296,
 'Linda': 8138,
 'pilgrims': 23348,
 'ordained': 9492,
 'Calvert': 27949,
 'Grace': 4378,
 'metaphor': 21927,
 '##rdo': 16525,
 '98': 5103,
 '1890': 5522,
 'marketed': 11777,
 'Williamson': 14905,
 'however': 1649,
 '##imo': 12013,
 'outpost': 26411,
 '##manned': 25820,
 '##zak': 24996,
 'Coke': 19630,
 '##ING': 15740,
 '##heus': 25212,
 '##kner': 25300,
 'experienced': 4531,
 'leg': 3420,
 'Mar': 9751,
 'suicide': 5680,
 'Stones': 15165,
 'Foreign': 4201,
 'cruise': 11270,
 'census': 2314,
 '##ivation': 16617,
 'what': 1184,
 'Airlines': 8570,
 'Martial': 24800,
 'razor': 20015,
 'near': 1485,
 '##ya': 2315,
 'threat': 4433,
 'Scandinavian': 18936,
 'Plans': 17171,
 '##uka': 12658,
 '##acles': 18281,
 '##azed': 27625,
 'Reservation': 21542,
 'toe': 12514,
 'slice': 16346,
 'sheet': 6837,
 'spreads': 23237,
 'big': 1992,
 'Angola': 13833,
 'Agricultural': 10705,
 'OBE': 16611,
 'administration': 3469,
 'Side': 6383,
 '##∈': 28745,
 'Yerevan': 26082,
 'bucks': 26429,
 '##史': 28891,
 'Arabic': 4944,
 'applause': 24670,
 '##Ω': 28334,
 'muttering': 27619,
 '##sel': 11510,
 'fluorescent': 26163,
 'fracture': 22869,
 'XVI': 18406,
 'Э': 472,
 'Circus': 14537,
 'NZ': 23412,
 '##red': 4359,
 'steering': 10217,
 'distinguish': 10706,
 'diplomat': 11608,
 '##rophe': 24658,
 'exiled': 15116,
 'Israel': 3103,
 '##lore': 21425,
 'Lima': 13503,
 '##pment': 22115,
 'μ': 429,
 '##jid': 26151,
 'Edgar': 9407,
 'hugged': 10167,
 'capita': 8008,
 '##yoshi': 18724,
 'perspective': 7281,
 'delta': 20811,
 'OF': 11345,
 'rock': 2067,
 '35th': 22031,
 'until': 1235,
 'Teenage': 25830,
 'ứ': 761,
 '##ic': 1596,
 '##tant': 17071,
 '##gon': 7528,
 'central': 2129,
 '##anti': 25711,
 'disposition': 25622,
 '##found': 27794,
 'sweating': 21234,
 'Mathematical': 16298,
 'rift': 25414,
 '##mbo': 13685,
 'Vincenzo': 27854,
 'arguments': 9989,
 'Google': 7986,
 '##ls': 3447,
 'padded': 22862,
 'pioneers': 17735,
 '##uad': 18413,
 'schooling': 15113,
 '##ド': 28847,
 'Copper': 20657,
 'Telangana': 26695,
 'Hume': 22427,
 'businesses': 5028,
 '##ulata': 23811,
 'Bahadur': 24290,
 '##iddle': 25826,
 'Per': 14286,
 '##read': 11613,
 '##ble': 2165,
 'heaved': 21766,
 'darts': 26581,
 '##mum': 16268,
 '##onomy': 19608,
 '##slow': 20120,
 'Living': 7932,
 'killer': 7010,
 'rebel': 10474,
 'dice': 26104,
 '##bon': 8868,
 'Called': 20469,
 'glazed': 21856,
 'scar': 14161,
 'contaminated': 21636,
 '##get': 16609,
 'chronicle': 26539,
 'Remember': 9498,
 'windshield': 21522,
 'Back': 4388,
 '##ylon': 22099,
 'habitat': 6296,
 'Lesser': 19286,
 'landowner': 22370,
 'Rhythm': 15885,
 'ha': 5871,
 'tea': 5679,
 'Athena': 24481,
 'Ш': 471,
 '##lies': 7875,
 'hold': 2080,
 'Devi': 15545,
 '##uddin': 22717,
 'Shirley': 11281,
 'alley': 10959,
 'authors': 5752,
 'Challenger': 19322,
 'thy': 21153,
 'arrest': 6040,
 'Heroes': 11312,
 '##cimal': 27924,
 '##ydro': 19694,
 '##80': 18910,
 'Universidad': 17572,
 '##ables': 15759,
 'Harvest': 23119,
 'rays': 11611,
 '##HC': 15779,
 'Highways': 27204,
 'Electoral': 14282,
 'Alone': 14227,
 '##dheim': 21934,
 'inspired': 3768,
 '⟩': 883,
 '##viator': 26680,
 'Imam': 21765,
 'Vita': 25118,
 'structured': 15695,
 'snack': 23029,
 '##varo': 25751,
 'veil': 20945,
 'fishing': 5339,
 'robe': 11580,
 'escorted': 13539,
 'grin': 5207,
 'thief': 16529,
 'intensive': 12885,
 'charging': 13758,
 '##rots': 27460,
 'Carpenter': 13190,
 'unclear': 10527,
 'speeds': 10979,
 'Taylor': 3357,
 'Marlborough': 25398,
 'trader': 22574,
 'masculine': 15838,
 '##rogen': 26767,
 '##otic': 14426,
 '##base': 14017,
 'comparatively': 22673,
 'without': 1443,
 'Protected': 15344,
 'backup': 10441,
 'Mohan': 20165,
 'Baseball': 5079,
 '##linity': 25230,
 '##zam': 20123,
 'handles': 17180,
 '##rez': 18550,
 'beams': 13903,
 'Fair': 6632,
 'vitamin': 23971,
 '##ulp': 20510,
 'nation': 3790,
 'Asiatic': 27039,
 'mine': 2317,
 'intentional': 24629,
 'experimental': 6700,
 'Qin': 22495,
 '##smus': 23283,
 'cue': 18780,
 'reads': 9568,
 'Literature': 7594,
 'Hodges': 21539,
 '##rush': 15432,
 '##chy': 8992,
 'Thought': 15255,
 'communal': 17022,
 '##ket': 22523,
 'Warren': 5407,
 'Rowe': 22652,
 'rag': 26133,
 'Congress': 2757,
 '##ābād': 22651,
 'Central': 1970,
 'multimedia': 20680,
 'happens': 5940,
 'only': 1178,
 '##onal': 24059,
 'Hanson': 18334,
 'buffalo': 26700,
 'Meet': 16053,
 'newest': 15649,
 'rainforest': 24369,
 'Abbot': 17659,
 '##eth': 8767,
 '##light': 4568,
 'adventures': 12108,
 '##stillery': 28042,
 'pursuing': 12137,
 'holders': 14322,
 '##luded': 27567,
 'castles': 19282,
 'フ': 960,
 'cafeteria': 18698,
 'Salvation': 22781,
 'Jonas': 10693,
 'scholarship': 7084,
 'Fifth': 9638,
 'Gus': 13067,
 '##ák': 24154,
 'footballer': 3585,
 'Edwards': 6847,
 'locking': 16348,
 'ô': 266,
 'Clayton': 11867,
 'Eagles': 8507,
 'relaxing': 22187,
 'Alba': 24005,
 'consumption': 8160,
 'Thorn': 22428,
 'steaming': 23026,
 'Mario': 7734,
 'Ensemble': 12618,
 'imaging': 14377,
 'drawing': 4619,
 'Seine': 19461,
 'barrels': 14619,
 'Croix': 20719,
 'Dana': 11422,
 '##pont': 27006,
 'Afterwards': 13611,
 'Elementary': 5395,
 'oceans': 25909,
 'Buenos': 8883,
 'murmurs': 26792,
 '##sto': 12223,
 'often': 1510,
 'id': 25021,
 'loser': 19398,
 'schedule': 6030,
 'Bomber': 20707,
 '##data': 27922,
 'dialects': 12336,
 'highways': 12402,
 'emperor': 6821,
 'harp': 19960,
 '##oring': 17089,
 '##rin': 4854,
 'RFC': 15274,
 'signalling': 25498,
 'platinum': 11980,
 '##icus': 14191,
 'Commando': 20621,
 '##was': 20963,
 'theater': 5184,
 '##ba': 2822,
 'fifty': 5547,
 'debut': 1963,
 'Collin': 24565,
 'trends': 14652,
 'reviews': 3761,
 '##kt': 21270,
 'è': 254,
 'strode': 12455,
 'Teacher': 14208,
 'street': 2472,
 'Carlisle': 13939,
 'explosions': 20518,
 'Regent': 17626,
 'Elias': 16325,
 'Theodore': 10408,
 '##jn': 22923,
 'Kazan': 24427,
 'eager': 9582,
 'Dustin': 27381,
 'stirred': 14030,
 'scenery': 19335,
 'Boca': 26178,
 'Herb': 20780,
 'Wilmington': 18150,
 'thicker': 22174,
 'Stars': 6200,
 'refrain': 24296,
 'Spaniards': 23068,
 'misconduct': 26879,
 'Dickens': 21677,
 '##dain': 21314,
 'Moreover': 9841,
 'reserve': 4837,
 'pace': 6418,
 'lumber': 17306,
 '##path': 16606,
 '32nd': 22579,
 'Davey': 22618,
 'higher': 2299,
 '##ctive': 13851,
 'Uruguay': 11752,
 'boot': 10909,
 '##dicative': 26289,
 'compose': 18742,
 'McGraw': 27315,
 'overhead': 9008,
 'Lakers': 19713,
 'Théâtre': 18519,
 'furniture': 7373,
 'grouping': 23291,
 'typing': 26716,
 'enjoy': 5548,
 '1825': 11377,
 'intercourse': 26864,
 'genome': 15519,
 'pneumonia': 20673,
 'lied': 10118,
 'Düsseldorf': 19822,
 'cheer': 18456,
 'ministerial': 25672,
 '##robe': 25560,
 'nouns': 22270,
 'card': 3621,
 'state': 1352,
 '##ied': 4830,
 'Pueblo': 22514,
 'Period': 16477,
 'Konstantin': 26956,
 'senses': 9439,
 '##gna': 12149,
 'Cannes': 15451,
 'Carson': 9563,
 'Television': 4552,
 'Fleming': 14217,
 'encounters': 12270,
 'Parliamentary': 10628,
 'interpretation': 7628,
 '05': 4991,
 '150': 4214,
 '##12': 11964,
 '##usions': 27262,
 'We': 1284,
 '62': 5073,
 'Initially': 7245,
 'structural': 8649,
 'elevation': 6252,
 '##ann': 11657,
 'starred': 4950,
 'desktop': 18813,
 '##®': 28167,
 'tempo': 16655,
 'Experimental': 17635,
 'Tirana': 27759,
 'testified': 15627,
 'Penang': 24099,
 '##iver': 18053,
 '##yne': 10941,
 'seminal': 23046,
 'violating': 22128,
 '##iled': 11908,
 'things': 1614,
 '##eg': 12606,
 'squad': 4322,
 'unveiled': 11770,
 'guy': 2564,
 'lance': 27017,
 'Warning': 19680,
 '⁵': 803,
 'Aug': 16892,
 'Week': 6237,
 'atom': 18858,
 'emotionally': 15962,
 'intellectuals': 19798,
 'Felix': 9423,
 'corrupt': 14644,
 '##tale': 15903,
 'alignment': 12793,
 'less': 1750,
 'galaxy': 15593,
 'Caracas': 23947,
 '##ổ': 28656,
 'Academic': 10076,
 'lust': 13051,
 'incarcerated': 27437,
 '##stant': 16566,
 '##ん': 28823,
 '##愛': 28921,
 'marginal': 16404,
 'Initial': 20242,
 'Tunnel': 12872,
 '##rary': 23728,
 '##に': 28807,
 'double': 2702,
 'Kung': 24120,
 'tooth': 14051,
 '1680': 27723,
 'distributions': 23190,
 'Pit': 20008,
 'shake': 5854,
 'bonds': 10150,
 'synthesis': 11362,
 '<': 133,
 '##formatics': 27960,
 'specification': 14911,
 'Gamma': 23039,
 'Khorasan': 25961,
 'environmental': 4801,
 '##ir': 3161,
 'strength': 3220,
 'Book': 3168,
 'sparked': 14514,
 '##VC': 19076,
 'speakers': 7417,
 'precinct': 26757,
 'Apache': 16995,
 'graceful': 21620,
 'ち': 909,
 '##bolt': 24850,
 'Archipelago': 26951,
 'bushes': 15479,
 'Primary': 6933,
 '##noy': 21244,
 'drank': 10741,
 'not': 1136,
 'offence': 16273,
 '##cats': 21393,
 'interim': 10572,
 '##erus': 27955,
 'Flight': 6945,
 '##KS': 25370,
 'reservoirs': 26536,
 '##hren': 22165,
 'Officers': 13236,
 'Jamal': 27440,
 'Volume': 6849,
 'Becky': 15009,
 '##gia': 9037,
 '⁷': 805,
 '##H1': 27012,
 '##IR': 18172,
 '##gonal': 22976,
 'relates': 15286,
 '##wives': 26791,
 '##ione': 23997,
 '≈': 860,
 'backward': 8740,
 'considerable': 5602,
 'Alabama': 5359,
 'immortal': 15642,
 'chain': 4129,
 '##bah': 25547,
 '##ganj': 25060,
 '##ulture': 15936,
 'obvious': 5119,
 'unhappy': 13143,
 '##nks': 18683,
 '‘': 786,
 'feeds': 15044,
 '##tera': 17528,
 'childhood': 5153,
 'た': 908,
 'pressing': 7675,
 'milk': 6831,
 'Vince': 12279,
 'Switzerland': 4507,
 'audience': 3703,
 'customs': 10148,
 'Pasadena': 20458,
 '##·': 28172,
 '##hman': 16277,
 '囗': 1003,
 'San': 1727,
 'Set': 9617,
 'Concert': 10325,
 '##]': 28149,
 'survive': 5195,
 'Mandy': 19599,
 '[unused59]': 59,
 '##foot': 10744,
 'trailed': 11133,
 'Scholar': 17052,
 'geography': 14534,
 '##plain': 18220,
 '##eds': 15513,
 'operative': 13035,
 'honor': 3874,
 'vehicles': 4011,
 'Ramsay': 21178,
 'bureau': 18561,
 'و': 592,
 'coastal': 5869,
 'FDA': 18762,
 'pipes': 13655,
 'Lehigh': 25912,
 '##iji': 23784,
 'Hazel': 21021,
 'Brisbane': 7217,
 'assassins': 27459,
 'chromosome': 18697,
 '##ivate': 18851,
 'Lok': 14444,
 'charted': 12883,
 'baptism': 24111,
 'Serbia': 6689,
 'systematic': 12818,
 'VHS': 18808,
 'Johannes': 12697,
 '##isan': 21599,
 'donations': 11725,
 'nightmares': 18118,
 'Metropolitan': 5458,
 'Duchy': 13019,
 'Gun': 11274,
 'requirements': 5420,
 '##imed': 24733,
 'ч': 498,
 'answers': 6615,
 'Poles': 17410,
 'economical': 24977,
 '##ric': 4907,
 'Melody': 14653,
 'negatively': 21598,
 'Baroque': 12869,
 'Michigan': 3312,
 'newly': 3599,
 'Cha': 24705,
 'ן': 549,
 '##ń': 19339,
 '##hiva': 22268,
 'Regan': 18090,
 'Fletcher': 10487,
 'distribute': 17114,
 'Cary': 22527,
 'residue': 24456,
 'enterprises': 14839,
 '##ს': 28608,
 '##খ': 28545,
 'breathless': 19305,
 '##ido': 12894,
 ...}

In [6]:
vocab_df = pd.DataFrame({'token':vocab.keys() , 'id':vocab.values()})
vocab_df.head()

     token     id
0      ##ッ  28843
1      ##§  28161
2      Tex  18033
3  sliding   7989
4       AB  16151

In [7]:
token_id = tokenizer.encode(sentence)
token_id

[101,
 1332,
 1297,
 3114,
 1128,
 22782,
 1116,
 117,
 1274,
 169,
 189,
 1294,
 22782,
 3556,
 102]

In [8]:
len(tokens)

13

In [9]:
len(token_id)

15

In [10]:
vocab_df.iloc[101]

token    Institutes
id            24496
Name: 101, dtype: object

In [11]:
list(zip(tokens,token_id[1:-1]))

[('When', 1332),
 ('life', 1297),
 ('gives', 3114),
 ('you', 1128),
 ('lemon', 22782),
 ('##s', 1116),
 (',', 117),
 ('don', 1274),
 ('`', 169),
 ('t', 189),
 ('make', 1294),
 ('lemon', 22782),
 ('##ad', 3556)]

In [12]:
tokenizer.decode(token_id)

'[CLS] When life gives you lemons, don ` t make lemonad [SEP]'

In [13]:
tokenizer_out = tokenizer(sentence)
tokenizer_out

{'input_ids': [101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1274, 169, 189, 1294, 22782, 3556, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [14]:
sentence2 = sentence.replace('don`t', '')

In [15]:
tokenizer_2 = tokenizer([sentence,sentence2],padding = True)
tokenizer_2

{'input_ids': [[101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1274, 169, 189, 1294, 22782, 3556, 102], [101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1294, 22782, 3556, 102, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]}

In [16]:
text = 'Tokenize me this please'

In [17]:
encoded_inputs = tokenizer(text, return_tensors='pt')
encoded_inputs

{'input_ids': tensor([[ 101, 1706, 6378, 3708, 1143, 1142, 4268,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [18]:
output = model(**encoded_inputs)

In [19]:
last_hidden_state = output.last_hidden_state
last_hidden_state

tensor([[[ 6.3545e-01,  1.7615e-01,  6.1589e-01,  ..., -1.1664e-01,
           5.5535e-01, -2.4577e-01],
         [ 2.6871e-01,  1.0804e-01, -7.9291e-02,  ...,  8.8401e-02,
           8.2027e-01, -7.8425e-04],
         [ 5.9982e-02,  5.7306e-01, -2.6445e-01,  ...,  2.0249e-01,
          -8.9708e-01,  2.3878e-01],
         ...,
         [-1.6705e-01,  3.0571e-01,  4.3537e-01,  ...,  8.0311e-02,
           2.3093e-01,  1.8002e-01],
         [ 4.5541e-01,  1.2220e-01,  5.8000e-01,  ...,  3.0526e-01,
           5.1684e-01, -2.6089e-01],
         [ 7.1148e-01,  3.9667e-02,  3.6133e-01,  ..., -4.8748e-01,
           5.2401e-01, -8.0548e-01]]], grad_fn=<NativeLayerNormBackward0>)

In [20]:
pooler_output = output.pooler_output
pooler_output

tensor([[-0.7571,  0.5197,  0.9999, -0.9967,  0.9707,  0.9701,  0.9926, -0.9949,
         -0.9859, -0.6731,  0.9896,  0.9993, -0.9988, -0.9999,  0.8604, -0.9850,
          0.9931, -0.5585, -1.0000, -0.5781, -0.6435, -0.9999,  0.1552,  0.9768,
          0.9878,  0.1029,  0.9929,  1.0000,  0.8974, -0.2188,  0.2532, -0.9955,
          0.8232, -0.9994,  0.1654,  0.1601,  0.6032, -0.2848,  0.7803, -0.9705,
         -0.7546, -0.4581,  0.6860, -0.5660,  0.9705,  0.2324,  0.0123,  0.0351,
          0.0350,  0.9999, -0.9770,  0.9985, -0.9960,  0.9980,  0.9982,  0.4647,
          0.9974,  0.1615, -0.9992,  0.3755,  0.9722,  0.2300,  0.9536, -0.2489,
          0.3661, -0.5718, -0.8706,  0.1662, -0.5311,  0.3377,  0.3172,  0.3148,
          0.9917, -0.9334, -0.0862, -0.9375,  0.0015, -0.9999,  0.9716,  1.0000,
          0.7328, -0.9998,  0.9978, -0.2295, -0.7797,  0.6083, -0.9990, -0.9997,
          0.1160, -0.6008,  0.9560, -0.9938,  0.7354, -0.9208,  1.0000, -0.9690,
         -0.1394,  0.4528,  0.9750, -0.7369, -0.8027,  0.9532,  0.9992, -0.9949,
          0.9989,  0.7893, -0.9579, -0.9086,  0.7907,  0.1189,  0.9945, -0.9915,
         -0.9258,  0.0540,  0.9790, -0.9037,  0.9951,  0.6319, -0.3201,  1.0000,
         -0.2164,  0.9681,  0.9993,  0.8552, -0.8630, -0.1896, -0.6129,  0.9199,
         -0.5439, -0.5080,  0.7987, -0.9956, -0.9986,  0.9998, -0.2904,  1.0000,
         -0.9996,  0.9966, -1.0000, -0.8288, -0.8360, -0.0029, -0.9900,  0.1884,
          0.9947,  0.0765, -0.9738, -0.8921,  0.5486, -0.8889,  0.6414,  0.7967,
         -0.9837,  0.9955,  0.9978,  0.9709,  0.9908,  0.1770, -0.9699,  0.9345,
          0.9930, -0.9998,  0.7275, -0.9964,  0.9996,  0.9818,  0.7734, -0.9964,
          0.9999, -0.6898, -0.0486, -0.2404, -0.0845, -0.9992,  0.5061,  0.3866,
          0.8177,  0.9997, -0.9976,  0.9996,  0.9540,  0.0023,  0.8341,  0.9991,
         -0.9982, -0.9891, -0.9931,  0.2792,  0.7637,  0.6106,  0.3757,  0.9725,
          0.9989,  0.7837, -0.9987, -0.3490,  0.9887, -0.2241,  1.0000, -0.4741,
         -0.9999, -0.7258,  0.9569,  0.9916, -0.3072,  0.9892, -0.7812, -0.1176,
          0.9900, -0.9951,  0.9982,  0.3805,  0.9100,  0.9016,  0.9971, -0.8809,
         -0.1179,  0.2488, -0.7342,  0.9999, -0.9998, -0.1622,  0.5727, -0.9965,
         -0.9991,  0.9923,  0.0035, -0.8535, -0.2706,  0.7472,  0.3042,  0.9468,
          0.9956, -0.6432, -0.6999, -0.9999, -0.9972, -0.8861, -0.9700,  0.1222,
          0.6960, -0.3968, -0.9467, -0.9987,  0.9813,  0.8097, -0.9506, -0.2361,
         -0.6971, -0.9987,  0.3860, -0.8952, -0.9989,  0.9998, -0.8629,  0.9972,
          0.9824, -0.9974,  0.8285, -0.9990, -0.0276, -0.9979,  0.3453,  0.6966,
         -0.7146,  0.0356,  0.9966, -0.9814, -0.8772,  0.8763, -1.0000,  0.9599,
         -0.2212,  0.9996,  0.7945, -0.0016,  0.9911,  0.9540, -0.9910, -0.9999,
          0.9584,  0.9716, -0.9968, -0.2010,  1.0000, -0.9982, -0.8485, -0.9731,
         -0.9978, -0.9998,  0.2274, -0.7957,  0.1766,  0.9910,  0.3693,  0.1538,
          0.9971,  0.9969,  0.1848, -0.2017,  0.0316, -0.9887, -0.9849,  0.8403,
          0.2262, -1.0000,  0.9999, -0.9975,  0.9977,  0.9588, -0.9961,  0.8365,
          0.0820, -0.9739,  0.0583,  0.9999,  0.9920, -0.0178,  0.1314,  0.9258,
         -0.3291,  0.6373, -0.8069, -0.7123,  0.1816, -0.9515,  0.9944,  0.8435,
         -0.9962,  0.9971,  0.0223,  0.8430, -0.8664,  0.9275,  0.9962, -0.1306,
         -0.5234, -0.0942, -0.5088, -0.9850,  0.1606, -0.9973, -0.5116,  0.8939,
          0.9950, -0.9945,  0.9961, -0.2122,  0.9520, -0.9981,  1.0000, -0.9990,
          0.1373,  0.7074, -0.8190, -0.7289,  0.9963,  0.9873,  0.9868, -0.9696,
         -0.7980,  0.8918,  0.9827, -0.9810,  0.0216, -0.9994, -0.8124,  0.9980,
          0.9970, -0.0297, -0.3829, -0.9980,  0.9733, -0.8571, -0.9477, -0.1020,
         -0.9060,  0.8072,  0.9983, -0.7311,  0.7485,  0.0850, -0.9948,  0.9285,
          0.7695,  0.9999, -0.9878,  0.4792,  0.9946, -0.2842, -0.7827,  0.6173,
          0.9994, -0.9810, -0.2885, -0.9998,  0.0882, -0.7892, -0.0856, -0.2855,
          0.1612, -0.8750,  0.9784,  0.0583,  0.8608, -0.2981,  0.9860,  0.0941,
         -0.0199, -0.3592, -0.3529,  0.5728,  0.1778,  0.9927, -0.9869,  0.9998,
         -0.3991, -1.0000, -0.9974, -0.8540, -0.9997,  0.7324, -0.9974,  0.9942,
          0.9693, -0.9984, -0.9994, -0.9992, -0.9973,  0.8477,  0.7326, -0.0584,
          0.3667,  0.3359,  0.0792, -0.0218, -0.0274, -0.9620, -0.5167, -0.9985,
          0.7891, -1.0000, -0.8156,  0.9981, -0.9967, -0.8957, -0.9610, -0.9234,
         -0.8407,  0.6460,  0.9922, -0.3712, -0.6447, -0.9997,  0.9939, -0.7828,
          0.1627, -0.8981, -0.9862,  0.9998,  0.9534, -0.1952, -0.1010, -0.9994,
          0.9908, -0.9236, -0.9433, -0.9916,  0.2077, -0.9675, -0.9999, -0.0030,
          0.9971,  0.9978,  0.9860,  0.2784, -0.4012, -0.9569,  0.2485, -1.0000,
          0.8845,  0.8966, -0.9927, -0.7827,  0.9960,  0.9894, -0.9623, -0.9864,
          0.9782,  0.3764,  0.9776, -0.6116, -0.5734,  0.3542, -0.0645, -0.9943,
         -0.9721,  0.9984, -0.9993,  0.9866,  0.9976,  0.9991, -0.1521,  0.1320,
         -0.9898, -0.9955, -0.6499,  0.3694, -1.0000,  0.9999, -1.0000,  0.5491,
         -0.8240,  0.9129,  0.9945, -0.4654, -1.0000, -0.9999,  0.3485,  0.0081,
          0.9960,  0.2759,  0.3342, -0.6858,  0.2105,  0.9990, -0.6438, -0.8236,
         -0.9985,  0.9998,  0.6440, -0.9995,  0.9965, -0.9997,  0.9056,  0.9894,
          0.9542,  0.9882, -0.9992,  1.0000, -0.9999,  0.9983, -1.0000, -0.9992,
          0.9999, -0.9956, -0.8023, -0.9999, -0.9985,  0.6966,  0.1030, -0.5456,
          0.9961, -0.9999, -0.9994, -0.3406, -0.9333, -0.8226,  0.9959, -0.6732,
          0.9964, -0.1598,  0.9662,  0.3991,  0.9980,  0.9984, -0.8217, -0.8651,
         -0.9963,  0.9909, -0.6722,  0.4460,  0.9823, -0.0578, -0.8412,  0.4005,
         -0.9987,  0.5920, -0.4776,  0.9351,  0.9175,  0.8852, -0.0546, -0.5004,
         -0.2392, -0.9975,  0.6273, -0.9998,  0.9916, -0.9578,  0.1025, -0.4840,
          0.4481, -0.9555,  0.9998,  0.9993, -0.9986,  0.1025,  0.9945, -0.8007,
          0.9881, -0.9963,  0.1006,  0.9767, -0.7371,  0.9916,  0.1164, -0.1511,
          0.9901, -0.9979, -0.9276, -0.7437,  0.4054,  0.2443, -0.9837,  0.1230,
          0.9890, -0.3768, -0.9999,  0.9695, -0.9997, -0.1793,  0.9889,  0.1082,
          1.0000, -0.8352,  0.1009,  0.1437, -0.9999, -0.9993,  0.1010, -0.1563,
         -0.9297,  0.9993, -0.2370,  0.8603, -0.9999,  0.3307,  0.9970,  0.3393,
          0.9028, -0.8580, -0.9738, -0.9762, -0.6804,  0.0464,  0.9261, -0.9905,
         -0.8090, -0.8957,  1.0000, -0.9991, -0.9553, -0.9953,  0.4388,  0.9319,
          0.4935,  0.0182, -0.9344,  0.9432, -0.9575,  0.9983, -0.9981, -0.9985,
          0.9999,  0.4540, -0.9958,  0.3697, -0.3319,  0.4963,  0.0590,  0.8047,
         -0.9039, -0.2252, -0.9987,  0.5132, -0.8915, -0.9951, -0.6478, -0.3970,
         -0.9967,  0.9975,  0.9855,  1.0000, -0.9999,  0.8953,  0.0767,  0.9995,
          0.0456, -0.7227,  0.9297,  0.9998, -0.7987,  0.8162, -0.0540, -0.0699,
          0.3983, -0.5634,  0.9978, -0.9397,  0.3580, -0.9913, -1.0000,  1.0000,
         -0.0789,  0.9941,  0.2283,  0.8258, -0.9260,  0.9846, -0.9897, -0.9264,
         -1.0000,  0.2482, -0.9988, -0.9952,  0.0202,  0.9952, -0.9998, -0.9957,
         -0.2742, -1.0000,  0.9035, -0.9914, -0.8678, -0.9947,  0.9978, -0.3438,
         -0.7682,  0.9893, -0.9866,  0.9619,  0.9178,  0.0304,  0.2780,  0.1900,
         -0.7325, -0.9961, -0.9547, -0.9828,  0.7925, -0.9946, -0.9150,  0.9984,
          0.9940, -0.9996, -0.9983,  0.9970,  0.1111,  0.9962, -0.6271, -0.9999,
         -1.0000,  0.1750, -0.0738,  0.9981, -0.4339,  0.9905,  0.8078, -0.5150,
          0.6823, -0.6820, -0.3612, -0.4140, -0.2183,  1.0000, -0.8331,  0.9958]],
       grad_fn=<TanhBackward0>)

In [21]:
def predict(text):
  encoded_inputs = tokenizer(text,return_tensors='pt')

  return model(**encoded_inputs)[0]
sentence_1 = 'my name is aditya'
sentence_2 = 'what are you doing'

In [23]:
print(out1.shape)
print(out2.shape)

torch.Size([1, 8, 768])
torch.Size([1, 6, 768])

In [24]:
tokens1 = tokenizer.tokenize(sentence_1)
tokens2 = tokenizer.tokenize(sentence_2)

In [25]:
print(tokens1)
print(tokens2)

['my', 'name', 'is', 'ad', '##ity', '##a']
['what', 'are', 'you', 'doing']

In [29]:
emb = out1[0:, tokens1.index('name'), :].detach()
emb

tensor([[ 6.7967e-03, -4.7840e-02,  1.5943e-01,  1.5315e-01,  2.6451e-02,
          1.0073e-02,  3.7702e-01, -3.7671e-01,  5.8345e-01, -3.8995e-01,
         -2.1744e-02,  7.8322e-01,  3.8983e-02,  3.7204e-01, -1.8876e-01,
          2.4810e-01,  1.0503e-01,  1.5540e-02,  4.1357e-01,  1.1790e-01,
         -2.6546e-01, -1.4298e-01,  1.0904e-01, -1.5613e-01,  8.4355e-02,
         -5.2573e-01,  4.5395e-01,  8.4557e-01,  4.3716e-03,  2.8941e-01,
          1.8594e-01, -1.3061e-02, -3.1456e-01, -1.0287e-01, -6.2651e-01,
         -3.2087e-01,  2.0904e-01,  2.5676e-01,  1.5797e-01, -2.5914e-01,
          9.7465e-02, -1.5056e-01,  6.3346e-01,  2.0006e-01, -3.2625e-01,
          2.8057e-01,  3.1665e-01, -5.1979e-02, -5.6782e-01, -1.8859e-01,
         -2.6256e-01, -2.4563e-01, -2.4067e-01, -3.1601e-01,  2.0720e-02,
         -1.0926e-01,  4.5926e-02, -3.6774e-02,  1.3036e-02,  6.6008e-01,
         -2.2611e-01,  1.6450e-01,  2.5502e-01,  1.2774e-01, -2.0683e-01,
          4.6024e-01, -5.8333e-01,  2.7040e-01,  1.4824e-01, -4.0395e-01,
          6.4238e-03, -3.1777e-01, -2.3875e-01,  3.0443e-01, -3.9099e-02,
         -9.6430e-02,  2.3325e-01,  1.6376e-01, -3.1492e-01, -5.5788e-01,
         -9.9421e-02,  2.6197e-01, -3.8885e-01, -1.2247e-01, -1.6256e-01,
          2.1441e-02, -5.3343e-02, -1.1121e-01, -2.4386e-01,  2.5165e-01,
          5.5744e-01, -2.9034e-01, -5.3818e-03, -5.1262e-01, -4.8293e-03,
          5.7333e-01,  8.1922e-02, -6.5056e-01,  9.7361e-02,  1.3392e-01,
          1.7002e-01,  2.3780e-01,  3.9879e-01, -2.4782e-01,  2.9255e-01,
         -2.0407e-01,  4.4792e-02, -3.5993e-01,  2.2961e-01,  5.1941e-01,
          1.8025e-01, -2.7413e-01,  1.0909e-01, -4.5311e-01, -3.0489e-01,
          9.8749e-02, -5.5128e-02,  5.6948e-01,  1.3493e-01, -3.9356e-01,
         -1.6745e-01,  1.6194e-01,  3.3745e-01, -2.9119e-01,  1.2974e-01,
         -2.7737e-01, -1.2578e-01, -4.1860e-01,  5.3323e-01, -9.0672e-02,
         -1.0826e-01, -2.3648e-01, -5.5921e-02, -6.7945e-01,  5.1796e-01,
         -1.9485e-01, -3.8857e-01,  3.3152e-02, -8.1911e-01,  1.9039e-01,
          2.2954e-01, -4.5061e-01,  3.0210e-01, -3.4153e-02,  2.2168e-01,
          1.1978e-01,  1.6730e-01,  2.0749e-01,  1.2723e-01,  9.3255e-02,
          5.4170e-02,  1.3686e-02,  7.7379e-02,  7.8922e-01,  1.7435e-01,
         -1.4440e-01,  2.1038e-01,  2.2158e-01,  7.6643e-01, -2.8187e-01,
          1.9280e-01, -5.5810e-02, -1.9771e-02,  5.8431e-02, -1.5045e-01,
         -2.6981e-01,  2.4431e-01,  1.7057e-01, -6.3525e-02,  3.1141e-01,
          4.1725e-02,  5.0629e-01, -7.8005e-01,  5.6368e-01,  6.7693e-02,
         -2.6085e-01,  4.8819e-01, -2.7183e-01, -2.3721e-02,  5.8350e-01,
          4.1926e-01,  4.3457e-01, -1.2053e-01, -2.5403e-01, -2.0332e-01,
         -4.1521e-01,  2.8700e-01,  1.1915e-01, -1.0220e-01,  7.0153e-01,
          1.2240e-01, -1.2572e-01, -4.1037e-01,  2.0986e-01,  4.4260e-01,
         -1.2607e-01, -5.0615e-03, -4.0440e-01,  9.0927e-02,  1.8349e-01,
         -1.9428e-01,  6.2329e-02, -4.3528e-01,  7.1510e-01, -3.9825e-03,
          3.5719e-01,  3.7513e-01, -3.4959e-01, -2.0020e-01, -6.3252e-01,
         -2.8376e-01, -8.1814e-01,  4.2229e-01, -2.1965e-01,  1.7864e-01,
         -4.1509e-01, -1.2828e-01, -3.0046e-01, -3.9419e-01,  1.2287e-01,
         -2.1253e-01, -2.7418e-01, -2.4015e-01,  3.3565e-01,  1.6660e-02,
          2.9369e-02, -1.7591e-01, -3.7586e-01, -6.4946e-02,  5.6052e-02,
          1.4928e-01,  4.7879e-01,  2.4213e-01, -4.2177e-01, -4.9637e-02,
         -5.5771e-02, -3.2705e-01,  1.3317e-01, -6.3466e-02,  4.3235e-01,
          9.6265e-02, -1.1189e-01,  6.5430e-01, -7.0234e-01,  1.2749e-02,
          5.2945e-01,  1.8302e-01,  5.9068e-01, -1.7452e-02, -2.4252e-02,
          3.5159e-01,  3.1849e-01, -4.7977e-01, -4.6436e-01,  5.0040e-01,
          9.1357e-02,  3.0093e-02,  2.6950e-01, -5.4937e-01, -1.3131e-01,
          2.8729e-01,  5.3031e-02, -3.2002e-01,  3.2852e-01, -1.4377e-01,
         -2.3160e-01, -2.7241e-01,  4.7794e-01, -1.0105e+00, -1.5545e-01,
         -2.4997e-01,  7.9948e-02, -1.5420e-02,  4.7507e-01, -3.9694e-01,
         -1.6997e-01, -1.7564e-01,  1.4245e-01, -1.4384e-01, -1.7155e-01,
          3.3275e-01, -1.5337e-01, -1.3421e-01,  1.8056e-01, -2.1134e-01,
          2.6246e-01,  5.7665e-01,  2.0629e-01, -2.0690e-01, -1.4354e-01,
          3.5738e-02,  9.9970e-02, -3.4575e-01,  2.9854e-02,  3.0449e-01,
          4.3499e-01, -2.5273e-01,  6.7791e-02,  7.4757e-02,  4.4032e-01,
          5.2755e-01,  2.3731e-01, -3.4669e-03, -2.7443e-01, -4.3723e-01,
         -5.8596e-02, -5.8296e-01,  4.6692e-01, -7.3940e-01,  1.9829e-01,
          2.8338e-01,  2.7149e-02, -1.6558e-01,  4.3412e-01, -1.0781e-01,
         -4.2600e-01, -1.9367e-01,  4.6264e-01, -2.0919e-01, -2.6288e-01,
         -1.2023e-01, -2.1111e-01,  3.1770e-02, -2.3325e-02,  1.3220e-02,
         -1.6577e-02, -8.6677e-01, -3.0354e-02, -1.7760e-01, -1.9616e-01,
          6.1303e-01, -2.6537e-02, -2.9414e-01,  1.4728e-01,  5.0429e-02,
         -1.9037e-01, -3.2978e-01,  3.0068e-01,  2.3351e-01,  1.2652e-01,
          2.0105e-01,  3.0743e-03, -1.8527e-01,  3.2452e-01, -3.0428e-01,
         -3.5022e-02,  9.1430e-02, -1.3159e-01, -1.1794e-01,  1.5278e-01,
         -1.9424e-01, -6.4989e-02, -5.2329e-01,  3.8642e-01,  8.9022e-02,
         -1.8068e-01, -2.1975e-01,  3.5715e-01, -3.7230e-02,  2.4739e-01,
         -3.6336e-01, -2.7763e-01, -2.1665e-01,  3.1244e-01,  2.0036e-01,
          9.9069e-02, -2.3268e-01, -4.2746e-01, -1.5778e-01, -1.1525e-01,
          9.0119e-02, -1.5133e-01,  3.5312e-01,  2.8677e-01,  2.2092e-01,
         -1.1191e-01, -1.0342e-01, -5.5763e-02,  2.2260e-01, -6.4800e-01,
         -3.7396e-02,  7.8870e-02,  5.2312e-01, -1.3335e-01, -4.4845e-01,
          3.2567e-01,  2.0386e-01, -3.4522e-01,  2.6044e-01, -4.3616e-01,
         -2.8112e-01, -2.4169e-01,  6.7931e-02, -6.1492e-01, -2.7410e-01,
         -4.0601e-02, -1.7945e-01,  4.0661e-01,  2.1131e-01, -5.4649e-01,
          1.3607e-01,  2.8684e-01,  1.0826e-01, -1.4827e-02, -9.5690e-01,
          8.0617e-02,  2.6989e-02,  5.3296e-01, -3.8564e-01, -1.8116e-01,
          1.3461e-01, -7.2654e-01,  2.8601e-01,  2.6373e-01, -3.0245e-01,
         -2.3695e-01, -2.2978e-01, -6.8899e-02,  4.9541e-01,  8.0766e-01,
          1.4717e-01, -2.0439e-01, -5.8388e-01, -4.5379e-01, -1.6514e-02,
          1.7614e-01,  6.9656e-02,  1.1323e-02, -3.3622e-01,  1.9258e-01,
          3.5146e-01,  6.1469e-01,  9.9333e-02, -2.9269e-01, -5.0564e-01,
          3.2788e-01,  6.9181e-02, -2.1278e-01,  1.1039e-01,  4.8314e-01,
         -4.8768e-01, -4.2606e-01,  5.2016e-01, -2.3955e-01, -1.9639e-02,
          1.6834e-01,  2.3090e-01,  2.4708e-02,  3.0886e-01,  5.4226e-02,
          9.1662e-02, -1.5943e-01,  5.8043e-01,  2.9612e-03,  3.8311e-01,
         -4.2614e-01, -7.2032e-01,  3.2194e-02, -1.5104e-02,  3.5380e-01,
         -1.2958e-01, -6.1329e-02, -1.5531e-01,  3.7353e-01,  2.0354e-02,
         -4.0917e-02,  9.5513e-02, -2.1143e-01, -5.3787e-01,  3.1538e-01,
         -7.8260e-02,  4.4706e-01,  5.1725e-01,  5.2416e-01, -7.0766e-01,
          1.8562e-01,  1.4359e-02,  1.3668e-01, -1.6941e-01,  6.7906e-02,
          2.9877e-01,  1.6688e-01, -1.9647e-01,  2.7760e-02,  1.8946e-01,
         -7.5942e-01, -6.3393e-01,  1.2918e-01,  1.3601e-01,  4.0726e-01,
          3.0074e-01,  2.2019e-01, -2.5755e-01,  2.7053e-01,  1.1872e-03,
          1.6418e-01, -2.8004e-01, -7.5670e-01, -3.2566e-01, -3.2290e-01,
         -3.9480e-01, -2.1363e-01,  1.7123e-01,  4.2052e-01, -9.3403e-02,
          1.7589e-01, -1.4607e-01, -2.0285e-01,  4.7363e-01, -3.8425e-01,
         -4.1455e-02, -9.6490e-01,  8.5963e-02,  1.4479e-01, -1.3222e-01,
         -1.6076e-01,  1.7801e-01, -2.9503e-02,  2.4516e-01, -4.1708e-01,
          6.5627e-01, -2.8382e-01, -7.0568e-01,  2.9143e-01,  1.6023e-01,
          1.3015e-01, -3.6557e-02,  3.2750e-01,  1.2922e-01,  1.6284e-01,
         -4.0144e-01,  3.7160e-01,  5.0174e-01, -3.1407e-01,  3.3786e-01,
         -6.0397e-02,  4.6243e-02,  4.6007e-01, -1.5594e-01,  4.2259e-01,
          4.7140e-01,  4.6187e-01,  6.9551e-02, -2.5020e-01,  3.6102e-01,
          4.7118e-01,  1.6735e-01,  6.5425e-01, -2.0612e-01,  2.9522e-01,
         -5.6583e-02,  6.0350e-01, -3.9642e-01,  8.4609e-01,  2.5253e-01,
         -1.3977e-01,  2.4036e-02, -9.1741e+00,  4.1225e-01,  3.4960e-01,
          7.9191e-01,  9.9380e-02, -8.3432e-02,  3.0665e-01,  7.1601e-02,
          5.0823e-01,  1.6366e-01, -1.4698e-01, -2.3457e-01, -2.8313e-01,
         -1.7080e-01, -2.8074e-01,  2.4058e-01,  3.1595e-02, -2.0108e-01,
         -1.9421e-01,  3.0115e-01,  6.5562e-02,  3.5686e-01, -3.7173e-02,
          8.5915e-02,  1.1444e-01, -2.8562e-01, -1.2385e-01,  1.0318e-01,
          1.6041e-01, -1.3797e-01, -4.0708e-02, -1.9270e-01,  2.8560e-01,
         -6.3669e-01,  2.9818e-01, -6.6801e-01, -9.5936e-02, -2.6271e-01,
          1.6508e-01, -3.2846e-01,  1.6008e-01, -7.5249e-04, -2.6796e-02,
         -1.6220e-01, -2.6355e-01, -1.9758e-01, -7.0680e-01,  8.8020e-02,
         -2.9766e-01,  3.7195e-01,  3.4239e-02,  3.3123e-01,  4.0090e-01,
          4.5943e-01, -2.4584e-01,  4.8162e-01,  1.8866e-01,  7.5138e-01,
          2.5627e-01,  5.1756e-01, -1.6694e-01, -4.9512e-01,  8.5865e-01,
         -2.9155e-01, -5.9659e-01, -5.1019e-02,  2.2059e-03, -1.3685e-01,
          4.1252e-01,  5.9163e-01, -4.3499e-03, -4.8351e-01, -1.0983e-01,
         -3.5767e-01, -9.4741e-02, -2.1483e-02,  1.3561e-01, -4.8949e-01,
         -6.0336e-02,  6.3753e-01, -3.9771e-01,  4.5033e-01,  3.0043e-01,
          2.4812e-01,  6.1918e-03, -4.6925e-01, -2.9702e-01,  5.0514e-02,
         -1.4919e-01,  2.4287e-01, -2.4185e-01,  1.0176e-01, -6.6559e-02,
         -2.8230e-02, -1.1388e-01,  2.4594e-01,  5.7975e-02,  3.2466e-02,
         -4.3975e-01,  6.7869e-02, -4.9085e-01,  3.2819e-02,  2.5490e-01,
         -6.7153e-01,  2.2852e-01,  1.5483e-01, -4.4261e-02,  1.6031e-01,
         -3.1190e-02, -3.5358e-01, -4.3602e-02, -7.4585e-01,  1.7251e-01,
          1.8326e-01,  2.8400e-01, -1.1627e-01,  3.2610e-01,  1.9802e-01,
          2.5407e-01,  3.7217e-01,  3.3436e-02,  2.6019e-01,  8.7400e-02,
          3.9038e-02,  2.8005e-01, -6.4401e-03, -2.2617e-01,  1.5130e-01,
         -8.3736e-02, -1.4597e-01,  5.9922e-01,  3.4039e-01, -2.9067e-01,
         -2.1355e-01,  1.0306e-01,  1.4735e-01, -7.8275e-02, -2.1602e-01,
         -7.2837e-01,  2.8692e-01, -1.8254e-01, -5.5325e-02,  7.4081e-02,
         -1.9936e-01,  3.5202e-01, -4.5307e-01, -8.6205e-02,  1.6909e-01,
         -4.5545e-01,  3.5958e-02, -9.7045e-02,  4.4887e-01, -2.0699e-01,
         -9.4467e-01, -7.3672e-04, -4.6198e-01,  5.2826e-01,  4.0959e-01,
         -3.4466e-01,  2.5073e-01,  1.7120e-01, -1.3428e-01, -4.8527e-02,
         -7.3074e-01, -1.1218e-01, -7.4274e-01, -1.5014e-01,  4.3295e-01,
         -4.7842e-02,  2.2459e-01,  4.3840e-01,  1.8372e-01,  4.0597e-01,
         -8.1849e-02, -4.4725e-01, -9.1167e-02,  5.2746e-01, -1.7675e-01,
          6.7393e-01, -1.1588e-01,  6.9148e-01,  1.5990e-01, -2.1405e-01,
          3.2160e-01,  4.3572e-01, -1.6151e-01, -3.1451e-02, -2.1630e-01,
         -1.5889e-01,  9.6171e-01, -1.0078e-01, -9.8218e-02, -1.2597e-01,
          7.0587e-02, -1.6493e-01,  4.1245e-01, -3.8619e-01,  4.1031e-01,
          8.2029e-02, -1.8456e-01,  2.2384e-01,  8.4850e-02, -4.6249e-02,
         -2.3021e-01,  2.1662e-01,  3.1965e-01,  4.0981e-01,  7.1919e-01,
          5.0057e-02,  2.1529e-01,  4.0365e-01]])

In [33]:
emb2 = out1[0:, tokens1.index('name'), :].detach()
emb2

tensor([[ 6.7967e-03, -4.7840e-02,  1.5943e-01,  1.5315e-01,  2.6451e-02,
          1.0073e-02,  3.7702e-01, -3.7671e-01,  5.8345e-01, -3.8995e-01,
         -2.1744e-02,  7.8322e-01,  3.8983e-02,  3.7204e-01, -1.8876e-01,
          2.4810e-01,  1.0503e-01,  1.5540e-02,  4.1357e-01,  1.1790e-01,
         -2.6546e-01, -1.4298e-01,  1.0904e-01, -1.5613e-01,  8.4355e-02,
         -5.2573e-01,  4.5395e-01,  8.4557e-01,  4.3716e-03,  2.8941e-01,
          1.8594e-01, -1.3061e-02, -3.1456e-01, -1.0287e-01, -6.2651e-01,
         -3.2087e-01,  2.0904e-01,  2.5676e-01,  1.5797e-01, -2.5914e-01,
          9.7465e-02, -1.5056e-01,  6.3346e-01,  2.0006e-01, -3.2625e-01,
          2.8057e-01,  3.1665e-01, -5.1979e-02, -5.6782e-01, -1.8859e-01,
         -2.6256e-01, -2.4563e-01, -2.4067e-01, -3.1601e-01,  2.0720e-02,
         -1.0926e-01,  4.5926e-02, -3.6774e-02,  1.3036e-02,  6.6008e-01,
         -2.2611e-01,  1.6450e-01,  2.5502e-01,  1.2774e-01, -2.0683e-01,
          4.6024e-01, -5.8333e-01,  2.7040e-01,  1.4824e-01, -4.0395e-01,
          6.4238e-03, -3.1777e-01, -2.3875e-01,  3.0443e-01, -3.9099e-02,
         -9.6430e-02,  2.3325e-01,  1.6376e-01, -3.1492e-01, -5.5788e-01,
         -9.9421e-02,  2.6197e-01, -3.8885e-01, -1.2247e-01, -1.6256e-01,
          2.1441e-02, -5.3343e-02, -1.1121e-01, -2.4386e-01,  2.5165e-01,
          5.5744e-01, -2.9034e-01, -5.3818e-03, -5.1262e-01, -4.8293e-03,
          5.7333e-01,  8.1922e-02, -6.5056e-01,  9.7361e-02,  1.3392e-01,
          1.7002e-01,  2.3780e-01,  3.9879e-01, -2.4782e-01,  2.9255e-01,
         -2.0407e-01,  4.4792e-02, -3.5993e-01,  2.2961e-01,  5.1941e-01,
          1.8025e-01, -2.7413e-01,  1.0909e-01, -4.5311e-01, -3.0489e-01,
          9.8749e-02, -5.5128e-02,  5.6948e-01,  1.3493e-01, -3.9356e-01,
         -1.6745e-01,  1.6194e-01,  3.3745e-01, -2.9119e-01,  1.2974e-01,
         -2.7737e-01, -1.2578e-01, -4.1860e-01,  5.3323e-01, -9.0672e-02,
         -1.0826e-01, -2.3648e-01, -5.5921e-02, -6.7945e-01,  5.1796e-01,
         -1.9485e-01, -3.8857e-01,  3.3152e-02, -8.1911e-01,  1.9039e-01,
          2.2954e-01, -4.5061e-01,  3.0210e-01, -3.4153e-02,  2.2168e-01,
          1.1978e-01,  1.6730e-01,  2.0749e-01,  1.2723e-01,  9.3255e-02,
          5.4170e-02,  1.3686e-02,  7.7379e-02,  7.8922e-01,  1.7435e-01,
         -1.4440e-01,  2.1038e-01,  2.2158e-01,  7.6643e-01, -2.8187e-01,
          1.9280e-01, -5.5810e-02, -1.9771e-02,  5.8431e-02, -1.5045e-01,
         -2.6981e-01,  2.4431e-01,  1.7057e-01, -6.3525e-02,  3.1141e-01,
          4.1725e-02,  5.0629e-01, -7.8005e-01,  5.6368e-01,  6.7693e-02,
         -2.6085e-01,  4.8819e-01, -2.7183e-01, -2.3721e-02,  5.8350e-01,
          4.1926e-01,  4.3457e-01, -1.2053e-01, -2.5403e-01, -2.0332e-01,
         -4.1521e-01,  2.8700e-01,  1.1915e-01, -1.0220e-01,  7.0153e-01,
          1.2240e-01, -1.2572e-01, -4.1037e-01,  2.0986e-01,  4.4260e-01,
         -1.2607e-01, -5.0615e-03, -4.0440e-01,  9.0927e-02,  1.8349e-01,
         -1.9428e-01,  6.2329e-02, -4.3528e-01,  7.1510e-01, -3.9825e-03,
          3.5719e-01,  3.7513e-01, -3.4959e-01, -2.0020e-01, -6.3252e-01,
         -2.8376e-01, -8.1814e-01,  4.2229e-01, -2.1965e-01,  1.7864e-01,
         -4.1509e-01, -1.2828e-01, -3.0046e-01, -3.9419e-01,  1.2287e-01,
         -2.1253e-01, -2.7418e-01, -2.4015e-01,  3.3565e-01,  1.6660e-02,
          2.9369e-02, -1.7591e-01, -3.7586e-01, -6.4946e-02,  5.6052e-02,
          1.4928e-01,  4.7879e-01,  2.4213e-01, -4.2177e-01, -4.9637e-02,
         -5.5771e-02, -3.2705e-01,  1.3317e-01, -6.3466e-02,  4.3235e-01,
          9.6265e-02, -1.1189e-01,  6.5430e-01, -7.0234e-01,  1.2749e-02,
          5.2945e-01,  1.8302e-01,  5.9068e-01, -1.7452e-02, -2.4252e-02,
          3.5159e-01,  3.1849e-01, -4.7977e-01, -4.6436e-01,  5.0040e-01,
          9.1357e-02,  3.0093e-02,  2.6950e-01, -5.4937e-01, -1.3131e-01,
          2.8729e-01,  5.3031e-02, -3.2002e-01,  3.2852e-01, -1.4377e-01,
         -2.3160e-01, -2.7241e-01,  4.7794e-01, -1.0105e+00, -1.5545e-01,
         -2.4997e-01,  7.9948e-02, -1.5420e-02,  4.7507e-01, -3.9694e-01,
         -1.6997e-01, -1.7564e-01,  1.4245e-01, -1.4384e-01, -1.7155e-01,
          3.3275e-01, -1.5337e-01, -1.3421e-01,  1.8056e-01, -2.1134e-01,
          2.6246e-01,  5.7665e-01,  2.0629e-01, -2.0690e-01, -1.4354e-01,
          3.5738e-02,  9.9970e-02, -3.4575e-01,  2.9854e-02,  3.0449e-01,
          4.3499e-01, -2.5273e-01,  6.7791e-02,  7.4757e-02,  4.4032e-01,
          5.2755e-01,  2.3731e-01, -3.4669e-03, -2.7443e-01, -4.3723e-01,
         -5.8596e-02, -5.8296e-01,  4.6692e-01, -7.3940e-01,  1.9829e-01,
          2.8338e-01,  2.7149e-02, -1.6558e-01,  4.3412e-01, -1.0781e-01,
         -4.2600e-01, -1.9367e-01,  4.6264e-01, -2.0919e-01, -2.6288e-01,
         -1.2023e-01, -2.1111e-01,  3.1770e-02, -2.3325e-02,  1.3220e-02,
         -1.6577e-02, -8.6677e-01, -3.0354e-02, -1.7760e-01, -1.9616e-01,
          6.1303e-01, -2.6537e-02, -2.9414e-01,  1.4728e-01,  5.0429e-02,
         -1.9037e-01, -3.2978e-01,  3.0068e-01,  2.3351e-01,  1.2652e-01,
          2.0105e-01,  3.0743e-03, -1.8527e-01,  3.2452e-01, -3.0428e-01,
         -3.5022e-02,  9.1430e-02, -1.3159e-01, -1.1794e-01,  1.5278e-01,
         -1.9424e-01, -6.4989e-02, -5.2329e-01,  3.8642e-01,  8.9022e-02,
         -1.8068e-01, -2.1975e-01,  3.5715e-01, -3.7230e-02,  2.4739e-01,
         -3.6336e-01, -2.7763e-01, -2.1665e-01,  3.1244e-01,  2.0036e-01,
          9.9069e-02, -2.3268e-01, -4.2746e-01, -1.5778e-01, -1.1525e-01,
          9.0119e-02, -1.5133e-01,  3.5312e-01,  2.8677e-01,  2.2092e-01,
         -1.1191e-01, -1.0342e-01, -5.5763e-02,  2.2260e-01, -6.4800e-01,
         -3.7396e-02,  7.8870e-02,  5.2312e-01, -1.3335e-01, -4.4845e-01,
          3.2567e-01,  2.0386e-01, -3.4522e-01,  2.6044e-01, -4.3616e-01,
         -2.8112e-01, -2.4169e-01,  6.7931e-02, -6.1492e-01, -2.7410e-01,
         -4.0601e-02, -1.7945e-01,  4.0661e-01,  2.1131e-01, -5.4649e-01,
          1.3607e-01,  2.8684e-01,  1.0826e-01, -1.4827e-02, -9.5690e-01,
          8.0617e-02,  2.6989e-02,  5.3296e-01, -3.8564e-01, -1.8116e-01,
          1.3461e-01, -7.2654e-01,  2.8601e-01,  2.6373e-01, -3.0245e-01,
         -2.3695e-01, -2.2978e-01, -6.8899e-02,  4.9541e-01,  8.0766e-01,
          1.4717e-01, -2.0439e-01, -5.8388e-01, -4.5379e-01, -1.6514e-02,
          1.7614e-01,  6.9656e-02,  1.1323e-02, -3.3622e-01,  1.9258e-01,
          3.5146e-01,  6.1469e-01,  9.9333e-02, -2.9269e-01, -5.0564e-01,
          3.2788e-01,  6.9181e-02, -2.1278e-01,  1.1039e-01,  4.8314e-01,
         -4.8768e-01, -4.2606e-01,  5.2016e-01, -2.3955e-01, -1.9639e-02,
          1.6834e-01,  2.3090e-01,  2.4708e-02,  3.0886e-01,  5.4226e-02,
          9.1662e-02, -1.5943e-01,  5.8043e-01,  2.9612e-03,  3.8311e-01,
         -4.2614e-01, -7.2032e-01,  3.2194e-02, -1.5104e-02,  3.5380e-01,
         -1.2958e-01, -6.1329e-02, -1.5531e-01,  3.7353e-01,  2.0354e-02,
         -4.0917e-02,  9.5513e-02, -2.1143e-01, -5.3787e-01,  3.1538e-01,
         -7.8260e-02,  4.4706e-01,  5.1725e-01,  5.2416e-01, -7.0766e-01,
          1.8562e-01,  1.4359e-02,  1.3668e-01, -1.6941e-01,  6.7906e-02,
          2.9877e-01,  1.6688e-01, -1.9647e-01,  2.7760e-02,  1.8946e-01,
         -7.5942e-01, -6.3393e-01,  1.2918e-01,  1.3601e-01,  4.0726e-01,
          3.0074e-01,  2.2019e-01, -2.5755e-01,  2.7053e-01,  1.1872e-03,
          1.6418e-01, -2.8004e-01, -7.5670e-01, -3.2566e-01, -3.2290e-01,
         -3.9480e-01, -2.1363e-01,  1.7123e-01,  4.2052e-01, -9.3403e-02,
          1.7589e-01, -1.4607e-01, -2.0285e-01,  4.7363e-01, -3.8425e-01,
         -4.1455e-02, -9.6490e-01,  8.5963e-02,  1.4479e-01, -1.3222e-01,
         -1.6076e-01,  1.7801e-01, -2.9503e-02,  2.4516e-01, -4.1708e-01,
          6.5627e-01, -2.8382e-01, -7.0568e-01,  2.9143e-01,  1.6023e-01,
          1.3015e-01, -3.6557e-02,  3.2750e-01,  1.2922e-01,  1.6284e-01,
         -4.0144e-01,  3.7160e-01,  5.0174e-01, -3.1407e-01,  3.3786e-01,
         -6.0397e-02,  4.6243e-02,  4.6007e-01, -1.5594e-01,  4.2259e-01,
          4.7140e-01,  4.6187e-01,  6.9551e-02, -2.5020e-01,  3.6102e-01,
          4.7118e-01,  1.6735e-01,  6.5425e-01, -2.0612e-01,  2.9522e-01,
         -5.6583e-02,  6.0350e-01, -3.9642e-01,  8.4609e-01,  2.5253e-01,
         -1.3977e-01,  2.4036e-02, -9.1741e+00,  4.1225e-01,  3.4960e-01,
          7.9191e-01,  9.9380e-02, -8.3432e-02,  3.0665e-01,  7.1601e-02,
          5.0823e-01,  1.6366e-01, -1.4698e-01, -2.3457e-01, -2.8313e-01,
         -1.7080e-01, -2.8074e-01,  2.4058e-01,  3.1595e-02, -2.0108e-01,
         -1.9421e-01,  3.0115e-01,  6.5562e-02,  3.5686e-01, -3.7173e-02,
          8.5915e-02,  1.1444e-01, -2.8562e-01, -1.2385e-01,  1.0318e-01,
          1.6041e-01, -1.3797e-01, -4.0708e-02, -1.9270e-01,  2.8560e-01,
         -6.3669e-01,  2.9818e-01, -6.6801e-01, -9.5936e-02, -2.6271e-01,
          1.6508e-01, -3.2846e-01,  1.6008e-01, -7.5249e-04, -2.6796e-02,
         -1.6220e-01, -2.6355e-01, -1.9758e-01, -7.0680e-01,  8.8020e-02,
         -2.9766e-01,  3.7195e-01,  3.4239e-02,  3.3123e-01,  4.0090e-01,
          4.5943e-01, -2.4584e-01,  4.8162e-01,  1.8866e-01,  7.5138e-01,
          2.5627e-01,  5.1756e-01, -1.6694e-01, -4.9512e-01,  8.5865e-01,
         -2.9155e-01, -5.9659e-01, -5.1019e-02,  2.2059e-03, -1.3685e-01,
          4.1252e-01,  5.9163e-01, -4.3499e-03, -4.8351e-01, -1.0983e-01,
         -3.5767e-01, -9.4741e-02, -2.1483e-02,  1.3561e-01, -4.8949e-01,
         -6.0336e-02,  6.3753e-01, -3.9771e-01,  4.5033e-01,  3.0043e-01,
          2.4812e-01,  6.1918e-03, -4.6925e-01, -2.9702e-01,  5.0514e-02,
         -1.4919e-01,  2.4287e-01, -2.4185e-01,  1.0176e-01, -6.6559e-02,
         -2.8230e-02, -1.1388e-01,  2.4594e-01,  5.7975e-02,  3.2466e-02,
         -4.3975e-01,  6.7869e-02, -4.9085e-01,  3.2819e-02,  2.5490e-01,
         -6.7153e-01,  2.2852e-01,  1.5483e-01, -4.4261e-02,  1.6031e-01,
         -3.1190e-02, -3.5358e-01, -4.3602e-02, -7.4585e-01,  1.7251e-01,
          1.8326e-01,  2.8400e-01, -1.1627e-01,  3.2610e-01,  1.9802e-01,
          2.5407e-01,  3.7217e-01,  3.3436e-02,  2.6019e-01,  8.7400e-02,
          3.9038e-02,  2.8005e-01, -6.4401e-03, -2.2617e-01,  1.5130e-01,
         -8.3736e-02, -1.4597e-01,  5.9922e-01,  3.4039e-01, -2.9067e-01,
         -2.1355e-01,  1.0306e-01,  1.4735e-01, -7.8275e-02, -2.1602e-01,
         -7.2837e-01,  2.8692e-01, -1.8254e-01, -5.5325e-02,  7.4081e-02,
         -1.9936e-01,  3.5202e-01, -4.5307e-01, -8.6205e-02,  1.6909e-01,
         -4.5545e-01,  3.5958e-02, -9.7045e-02,  4.4887e-01, -2.0699e-01,
         -9.4467e-01, -7.3672e-04, -4.6198e-01,  5.2826e-01,  4.0959e-01,
         -3.4466e-01,  2.5073e-01,  1.7120e-01, -1.3428e-01, -4.8527e-02,
         -7.3074e-01, -1.1218e-01, -7.4274e-01, -1.5014e-01,  4.3295e-01,
         -4.7842e-02,  2.2459e-01,  4.3840e-01,  1.8372e-01,  4.0597e-01,
         -8.1849e-02, -4.4725e-01, -9.1167e-02,  5.2746e-01, -1.7675e-01,
          6.7393e-01, -1.1588e-01,  6.9148e-01,  1.5990e-01, -2.1405e-01,
          3.2160e-01,  4.3572e-01, -1.6151e-01, -3.1451e-02, -2.1630e-01,
         -1.5889e-01,  9.6171e-01, -1.0078e-01, -9.8218e-02, -1.2597e-01,
          7.0587e-02, -1.6493e-01,  4.1245e-01, -3.8619e-01,  4.1031e-01,
          8.2029e-02, -1.8456e-01,  2.2384e-01,  8.4850e-02, -4.6249e-02,
         -2.3021e-01,  2.1662e-01,  3.1965e-01,  4.0981e-01,  7.1919e-01,
          5.0057e-02,  2.1529e-01,  4.0365e-01]])

In [27]:
out1 = predict(sentence_1)
out2 = predict(sentence_2)

In [30]:
sentence = "When life gives you lemons, don`t make lemonad"
tokens = tokenizer.tokenize(sentence)
token_id = tokenizer.encode(sentence)

print(f"Tokens: {tokens}")
print(f"Token IDs: {token_id}")
print(f"Length of tokens: {len(tokens)}")
print(f"Length of token IDs: {len(token_id)}")
print("\nThe token IDs include special tokens like [CLS] (101) at the beginning and [SEP] (102) at the end.")

Tokens: ['When', 'life', 'gives', 'you', 'lemon', '##s', ',', 'don', '`', 't', 'make', 'lemon', '##ad']
Token IDs: [101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1274, 169, 189, 1294, 22782, 3556, 102]
Length of tokens: 13
Length of token IDs: 15

The token IDs include special tokens like [CLS] (101) at the beginning and [SEP] (102) at the end.

In [31]:
sentence = "When life gives you lemons, don`t make lemonad"
tokens = tokenizer.tokenize(sentence)

# Find the index of the token 'lemons'
index_of_lemons = tokens.index('lemon')

print(f"Tokens: {tokens}")
print(f"Index of 'lemon': {index_of_lemons}")

Tokens: ['When', 'life', 'gives', 'you', 'lemon', '##s', ',', 'don', '`', 't', 'make', 'lemon', '##ad']
Index of 'lemon': 4

In [35]:
cosine(emb.squeeze(0),emb2.squeeze(0))

np.float32(0.0)